-- Fix the quotes table structure
-- Drop the existing table and recreate it with proper identity column

DROP TABLE IF EXISTS "quotes" CASCADE;

CREATE TABLE "quotes" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "text" text NOT NULL,
    "Author " text NOT NULL,
    "createdat" date NOT NULL,
    "userid" text NOT NULL,
    CONSTRAINT "FK_quotes_AspNetUsers_userid" FOREIGN KEY ("userid") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_quotes_userid" ON "quotes" ("userid");

-- Insert the migration record
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion") 
VALUES ('20250724222131_FixQuotesTableIdentity', '8.0.4') 
ON CONFLICT ("MigrationId") DO NOTHING; 