#!/bin/bash

echo "🚀 Running SQL script to create Quotes table..."

# The SQL commands to run
SQL_COMMANDS="
-- Create the Quotes table manually
CREATE TABLE \"Quotes\" (
    \"Id\" integer GENERATED BY DEFAULT AS IDENTITY,
    \"Text\" text NOT NULL,
    \"Author\" text NOT NULL,
    \"CreatedAt\" timestamp with time zone NOT NULL,
    \"UserId\" text NOT NULL,
    CONSTRAINT \"PK_Quotes\" PRIMARY KEY (\"Id\"),
    CONSTRAINT \"FK_Quotes_AspNetUsers_UserId\" FOREIGN KEY (\"UserId\") REFERENCES \"AspNetUsers\" (\"Id\") ON DELETE CASCADE
);

-- Create the index
CREATE INDEX \"IX_Quotes_UserId\" ON \"Quotes\" (\"UserId\");

-- Insert the migration record for the quotes table
INSERT INTO \"__EFMigrationsHistory\" (\"MigrationId\", \"ProductVersion\") 
VALUES ('20250724204221_AddQuotesTable', '8.0.4') 
ON CONFLICT (\"MigrationId\") DO NOTHING;
"

echo "📋 SQL Commands to run in Railway Database Console:"
echo "=================================================="
echo "$SQL_COMMANDS"
echo "=================================================="
echo ""
echo "🔗 Go to your Railway dashboard and run these commands in the database console."
echo "   Or copy and paste the commands above into your Railway PostgreSQL console." 