using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TestPraktik.Migrations
{
    /// <inheritdoc />
    public partial class FixQuotesTableProperly : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // First, drop the existing table and recreate it with proper identity column
            migrationBuilder.Sql(@"
                DROP TABLE IF EXISTS ""quotes"" CASCADE;
                
                CREATE TABLE ""quotes"" (
                    ""id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""text"" text NOT NULL,
                    ""Author "" text NOT NULL,
                    ""createdat"" date NOT NULL,
                    ""userid"" text NOT NULL,
                    CONSTRAINT ""FK_quotes_AspNetUsers_userid"" FOREIGN KEY (""userid"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
                );
                
                CREATE INDEX ""IX_quotes_userid"" ON ""quotes"" (""userid"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Revert by dropping the table
            migrationBuilder.Sql(@"
                DROP TABLE IF EXISTS ""quotes"" CASCADE;
            ");
        }
    }
}
